# This is a basic workflow to help you get started with Actions

name: Check microservice status

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Triggers the workflow on a 5 minute interval
  schedule:
    #(https://crontab.guru)
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  Gather_status:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check Grafana
        run: |
          ${{ secrets.GRAFANA-EDIT}}
   
     
