name: Check microservice status

on:
  ### Triggers the workflow on push to the "main" branch
  push:
    branches: [ "main" ]
  
  ### Triggers the workflow on the 15th minute of every hour - 9:15/10:15/11:15 etc
  schedule:
    #- cron: '*/6 * * * *' Old cron
    - cron: '15 */1 * * *'

  ### Uncomment to allow running this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  Gather_status:
    runs-on: ubuntu-latest
    steps:
        ### Setting the correct timezone so that that the time is correct in the notifications in Discord
      - name: Set timezone
        run: |
          sudo timedatectl set-timezone Europe/Belgrade
          
        ### Clean the previous runs in the Actions tabs
      - name: Clean previous runs
        run: |
          ${{ secrets.CLEAN_PREVIOUS_RUNS }}

        ### Check for a certain service - in this case Grafana
      - name: Check Grafana v2
        run: |
          ${{ secrets.GRAFANA_EDIT}}
   
     
